# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{filter_fu}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benedikt Deicke"]
  s.date = %q{2009-10-15}
  s.description = %q{This Ruby on Rails plugin adds a filtered_by method to your models. It accepts a hash of filters that are applied using named_scopes. In addition the plugin adds some view helpers to easily build filter forms.}
  s.email = %q{benedikt@synatic.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "filter_fu.gemspec",
     "lib/filter_fu.rb",
     "lib/filter_fu/active_record.rb",
     "lib/filter_fu/view_helper.rb",
     "rails/init.rb",
     "spec/active_record_spec.rb",
     "spec/db/database.yml",
     "spec/db/schema.rb",
     "spec/dummies.rb",
     "spec/filter_fu_spec.rb",
     "spec/fixtures/employee.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/view_helper_spec.rb"
  ]
  s.homepage = %q{http://github.com/benedikt/filter_fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Filter ActiveRecord models using named_scopes}
  s.test_files = [
    "spec/active_record_spec.rb",
     "spec/db/schema.rb",
     "spec/dummies.rb",
     "spec/filter_fu_spec.rb",
     "spec/fixtures/employee.rb",
     "spec/spec_helper.rb",
     "spec/view_helper_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
